

# This file was *autogenerated* from the file isogeny.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_27 = Integer(27); _sage_const_4 = Integer(4); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3); _sage_const_8 = Integer(8)
A = _sage_const_1 
B = _sage_const_2 
Abar = -_sage_const_27  * A
Bbar = _sage_const_4  * A + _sage_const_27  * B

E = EllipticCurve([_sage_const_0 ,A,_sage_const_1 ,-_sage_const_2 *B * A, B**_sage_const_2 ])
print(E)

Ebar = EllipticCurve([_sage_const_0 ,Abar,_sage_const_1 ,-_sage_const_2 *Bbar * Abar, Bbar**_sage_const_2 ])
print(Ebar)

def Phi(X, Y, x, y):
    A = _sage_const_2  * y**_sage_const_2  + _sage_const_2  * X * Y**_sage_const_2  - x**_sage_const_3  - _sage_const_2 /_sage_const_3  * X * x**_sage_const_2 
    xi = _sage_const_3 /(x**_sage_const_2 ) * A

    B = -_sage_const_4  * X * Y * x + _sage_const_8  * X * Y**_sage_const_2  - x**_sage_const_3 
    eta = _sage_const_27  * y / (x**_sage_const_3 )
    return (xi, eta)

plot(E + Ebar)

